# Generated by Django 5.2.4 on 2025-08-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('last_name', models.CharField(help_text='Apellido del cliente', max_length=100)),
                ('email', models.EmailField(help_text='Email del cliente', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Teléfono del cliente', max_length=20, null=True)),
                ('dni', models.CharField(help_text='DNI o documento de identidad', max_length=20, unique=True)),
                ('address', models.TextField(blank=True, help_text='Dirección del cliente', null=True)),
                ('birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True)),
                ('nationality', models.CharField(blank=True, help_text='Nacionalidad', max_length=50, null=True)),
                ('active', models.BooleanField(default=True, help_text='Si el cliente está activo en el sistema')),
                ('vip', models.BooleanField(default=False, help_text='Si es cliente VIP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
