# Generated by Django 5.2.4 on 2025-08-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Número de habitación', max_length=10, unique=True)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('double', 'Doble'), ('triple', 'Triple'), ('suite', 'Suite'), ('family', 'Familiar')], default='individual', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Número máximo de huéspedes')),
                ('status', models.CharField(choices=[('available', 'Libre'), ('occupied', 'Ocupada'), ('cleaning', 'En Limpieza'), ('maintenance', 'En Mantenimiento'), ('reserved', 'Reservada')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio por noche', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True, help_text='Si la habitación está disponible para reservas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['number'],
            },
        ),
    ]
