# Generated by Django 5.2.4 on 2025-08-04 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email del destinatario')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del destinatario')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('content', models.TextField(verbose_name='Contenido del email')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking', verbose_name='Reserva relacionada')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Cliente relacionado')),
            ],
            options={
                'verbose_name': 'Registro de Email',
                'verbose_name_plural': 'Registros de Email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_emaill_status_580ed7_idx'), models.Index(fields=['created_at'], name='core_emaill_created_be864d_idx'), models.Index(fields=['recipient_email'], name='core_emaill_recipie_e07add_idx')],
            },
        ),
    ]
