# Generated by Django 5.2.4 on 2025-11-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('core', '0002_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.hotel', verbose_name='Hotel'),
        ),
    ]