# Generated by Django 5.2.4 on 2025-11-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_hotelstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='plan_name',
            field=models.CharField(choices=[('starter', 'Starter 20'), ('grow', 'Grow 40')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='trial_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
