# Generated by Django 5.2.4 on 2025-08-04 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(help_text='Fecha de llegada')),
                ('check_out_date', models.DateField(help_text='Fecha de salida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Finalizada'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('partial', 'Pago Parcial'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('guests_count', models.PositiveIntegerField(default=1, help_text='Número de huéspedes')),
                ('special_requests', models.TextField(blank=True, help_text='Solicitudes especiales', null=True)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Precio total de la reserva', max_digits=10)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Fecha de confirmación', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Fecha de cancelación', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Motivo de cancelación', null=True)),
                ('client', models.ForeignKey(help_text='Cliente que realiza la reserva', on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('room', models.ForeignKey(help_text='Habitación reservada', on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['check_in_date', 'check_out_date'], name='bookings_bo_check_i_64cf26_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'), models.Index(fields=['client'], name='bookings_bo_client__0a6e46_idx')],
            },
        ),
    ]
